name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust nightly with miri
      run: rustup toolchain install nightly --component miri
    - name: Run tests for sync mode
      run: make test_sync
    - name: Run tests for async mode
      run: make test_async
#    - name: Run miri test for sync mode
#      run: make miri_test_all_sync
#    - name: Run miri test for async mode
#      run: make miri_test_all
